@startuml

hide circle
hide empty members

package "フォルダ階層構造" <<Frame>> {
entity ルートフォルダ  {
}

entity 要件定義  {
  + 要件定義書(太郎)
}
entity 設計  {
}
entity 基本設計  {
  + 画面設計書(次郎)
  + DB設計書(次郎)
}
entity 詳細設計  {
  + アプリ詳細設計書(次郎)
}
entity 実装  {
}
entity アプリ  {
}
entity 機能1  {
  + 機能1ソースコード(三郎)
  + 機能2ソースコード(三郎)
}

ルートフォルダ *-- 要件定義
ルートフォルダ *-- 設計
ルートフォルダ *-- 実装
設計 *-- 基本設計
設計 *-- 詳細設計
実装 *-- アプリ
アプリ*-- 機能1

@enduml