@startuml tables

entity Assignee {
  + id  [PK]
  --
  name
}

entity Issue {
  + id  [PK]
  --
  text
}

entity Issue_assignee{
  + id [PK]
  --
  assignee_id [FK]
  issue_id[FK]
}

Issue }o..|| Issue_assignee
Assignee ||..|| Issue_assignee


@enduml